//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HospitalModel1", "FK__check_up__med_id__173876EA", "medicines", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConsoleApplication1.medicine), "check_up", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConsoleApplication1.check_up), true)]
[assembly: EdmRelationshipAttribute("HospitalModel1", "FK__check_up__patien__15502E78", "patients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConsoleApplication1.patient), "check_up", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConsoleApplication1.check_up), true)]
[assembly: EdmRelationshipAttribute("HospitalModel1", "FK__check_up__treat___164452B1", "treatment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConsoleApplication1.treatment), "check_up", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConsoleApplication1.check_up), true)]

#endregion

namespace ConsoleApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HospitalEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HospitalEntities1 object using the connection string found in the 'HospitalEntities1' section of the application configuration file.
        /// </summary>
        public HospitalEntities1() : base("name=HospitalEntities1", "HospitalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HospitalEntities1 object.
        /// </summary>
        public HospitalEntities1(string connectionString) : base(connectionString, "HospitalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HospitalEntities1 object.
        /// </summary>
        public HospitalEntities1(EntityConnection connection) : base(connection, "HospitalEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<check_up> check_up
        {
            get
            {
                if ((_check_up == null))
                {
                    _check_up = base.CreateObjectSet<check_up>("check_up");
                }
                return _check_up;
            }
        }
        private ObjectSet<check_up> _check_up;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<equipment> equipments
        {
            get
            {
                if ((_equipments == null))
                {
                    _equipments = base.CreateObjectSet<equipment>("equipments");
                }
                return _equipments;
            }
        }
        private ObjectSet<equipment> _equipments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<medicine> medicines
        {
            get
            {
                if ((_medicines == null))
                {
                    _medicines = base.CreateObjectSet<medicine>("medicines");
                }
                return _medicines;
            }
        }
        private ObjectSet<medicine> _medicines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<patient> patients
        {
            get
            {
                if ((_patients == null))
                {
                    _patients = base.CreateObjectSet<patient>("patients");
                }
                return _patients;
            }
        }
        private ObjectSet<patient> _patients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<treatment> treatments
        {
            get
            {
                if ((_treatments == null))
                {
                    _treatments = base.CreateObjectSet<treatment>("treatments");
                }
                return _treatments;
            }
        }
        private ObjectSet<treatment> _treatments;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the check_up EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocheck_up(check_up check_up)
        {
            base.AddObject("check_up", check_up);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the equipments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToequipments(equipment equipment)
        {
            base.AddObject("equipments", equipment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the medicines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomedicines(medicine medicine)
        {
            base.AddObject("medicines", medicine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopatients(patient patient)
        {
            base.AddObject("patients", patient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the treatments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotreatments(treatment treatment)
        {
            base.AddObject("treatments", treatment);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="check_up")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class check_up : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new check_up object.
        /// </summary>
        /// <param name="check_id">Initial value of the check_id property.</param>
        /// <param name="patient_id">Initial value of the patient_id property.</param>
        /// <param name="treat_id">Initial value of the treat_id property.</param>
        /// <param name="med_id">Initial value of the med_id property.</param>
        public static check_up Createcheck_up(global::System.Int32 check_id, global::System.Int32 patient_id, global::System.Int32 treat_id, global::System.Int32 med_id)
        {
            check_up check_up = new check_up();
            check_up.check_id = check_id;
            check_up.patient_id = patient_id;
            check_up.treat_id = treat_id;
            check_up.med_id = med_id;
            return check_up;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 check_id
        {
            get
            {
                return _check_id;
            }
            set
            {
                if (_check_id != value)
                {
                    Oncheck_idChanging(value);
                    ReportPropertyChanging("check_id");
                    _check_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("check_id");
                    Oncheck_idChanged();
                }
            }
        }
        private global::System.Int32 _check_id;
        partial void Oncheck_idChanging(global::System.Int32 value);
        partial void Oncheck_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 patient_id
        {
            get
            {
                return _patient_id;
            }
            set
            {
                Onpatient_idChanging(value);
                ReportPropertyChanging("patient_id");
                _patient_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patient_id");
                Onpatient_idChanged();
            }
        }
        private global::System.Int32 _patient_id;
        partial void Onpatient_idChanging(global::System.Int32 value);
        partial void Onpatient_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String complains
        {
            get
            {
                return _complains;
            }
            set
            {
                OncomplainsChanging(value);
                ReportPropertyChanging("complains");
                _complains = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("complains");
                OncomplainsChanged();
            }
        }
        private global::System.String _complains;
        partial void OncomplainsChanging(global::System.String value);
        partial void OncomplainsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String findings
        {
            get
            {
                return _findings;
            }
            set
            {
                OnfindingsChanging(value);
                ReportPropertyChanging("findings");
                _findings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("findings");
                OnfindingsChanged();
            }
        }
        private global::System.String _findings;
        partial void OnfindingsChanging(global::System.String value);
        partial void OnfindingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 treat_id
        {
            get
            {
                return _treat_id;
            }
            set
            {
                Ontreat_idChanging(value);
                ReportPropertyChanging("treat_id");
                _treat_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("treat_id");
                Ontreat_idChanged();
            }
        }
        private global::System.Int32 _treat_id;
        partial void Ontreat_idChanging(global::System.Int32 value);
        partial void Ontreat_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 med_id
        {
            get
            {
                return _med_id;
            }
            set
            {
                Onmed_idChanging(value);
                ReportPropertyChanging("med_id");
                _med_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("med_id");
                Onmed_idChanged();
            }
        }
        private global::System.Int32 _med_id;
        partial void Onmed_idChanging(global::System.Int32 value);
        partial void Onmed_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private Nullable<global::System.Int32> _quantity;
        partial void OnquantityChanging(Nullable<global::System.Int32> value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> check_date
        {
            get
            {
                return _check_date;
            }
            set
            {
                Oncheck_dateChanging(value);
                ReportPropertyChanging("check_date");
                _check_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("check_date");
                Oncheck_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _check_date;
        partial void Oncheck_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncheck_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__med_id__173876EA", "medicines")]
        public medicine medicine
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<medicine>("HospitalModel1.FK__check_up__med_id__173876EA", "medicines").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<medicine>("HospitalModel1.FK__check_up__med_id__173876EA", "medicines").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<medicine> medicineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<medicine>("HospitalModel1.FK__check_up__med_id__173876EA", "medicines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<medicine>("HospitalModel1.FK__check_up__med_id__173876EA", "medicines", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__patien__15502E78", "patients")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("HospitalModel1.FK__check_up__patien__15502E78", "patients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("HospitalModel1.FK__check_up__patien__15502E78", "patients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("HospitalModel1.FK__check_up__patien__15502E78", "patients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("HospitalModel1.FK__check_up__patien__15502E78", "patients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__treat___164452B1", "treatment")]
        public treatment treatment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<treatment>("HospitalModel1.FK__check_up__treat___164452B1", "treatment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<treatment>("HospitalModel1.FK__check_up__treat___164452B1", "treatment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<treatment> treatmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<treatment>("HospitalModel1.FK__check_up__treat___164452B1", "treatment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<treatment>("HospitalModel1.FK__check_up__treat___164452B1", "treatment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="equipment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class equipment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new equipment object.
        /// </summary>
        /// <param name="equip_id">Initial value of the equip_id property.</param>
        public static equipment Createequipment(global::System.Int32 equip_id)
        {
            equipment equipment = new equipment();
            equipment.equip_id = equip_id;
            return equipment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 equip_id
        {
            get
            {
                return _equip_id;
            }
            set
            {
                if (_equip_id != value)
                {
                    Onequip_idChanging(value);
                    ReportPropertyChanging("equip_id");
                    _equip_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("equip_id");
                    Onequip_idChanged();
                }
            }
        }
        private global::System.Int32 _equip_id;
        partial void Onequip_idChanging(global::System.Int32 value);
        partial void Onequip_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String equip_name
        {
            get
            {
                return _equip_name;
            }
            set
            {
                Onequip_nameChanging(value);
                ReportPropertyChanging("equip_name");
                _equip_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("equip_name");
                Onequip_nameChanged();
            }
        }
        private global::System.String _equip_name;
        partial void Onequip_nameChanging(global::System.String value);
        partial void Onequip_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> requested_date
        {
            get
            {
                return _requested_date;
            }
            set
            {
                Onrequested_dateChanging(value);
                ReportPropertyChanging("requested_date");
                _requested_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("requested_date");
                Onrequested_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _requested_date;
        partial void Onrequested_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onrequested_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_defected
        {
            get
            {
                return _date_defected;
            }
            set
            {
                Ondate_defectedChanging(value);
                ReportPropertyChanging("date_defected");
                _date_defected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_defected");
                Ondate_defectedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_defected;
        partial void Ondate_defectedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_defectedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="medicine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class medicine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new medicine object.
        /// </summary>
        /// <param name="med_id">Initial value of the med_id property.</param>
        public static medicine Createmedicine(global::System.Int32 med_id)
        {
            medicine medicine = new medicine();
            medicine.med_id = med_id;
            return medicine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 med_id
        {
            get
            {
                return _med_id;
            }
            set
            {
                if (_med_id != value)
                {
                    Onmed_idChanging(value);
                    ReportPropertyChanging("med_id");
                    _med_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("med_id");
                    Onmed_idChanged();
                }
            }
        }
        private global::System.Int32 _med_id;
        partial void Onmed_idChanging(global::System.Int32 value);
        partial void Onmed_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String med_name
        {
            get
            {
                return _med_name;
            }
            set
            {
                Onmed_nameChanging(value);
                ReportPropertyChanging("med_name");
                _med_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("med_name");
                Onmed_nameChanged();
            }
        }
        private global::System.String _med_name;
        partial void Onmed_nameChanging(global::System.String value);
        partial void Onmed_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private Nullable<global::System.Int32> _quantity;
        partial void OnquantityChanging(Nullable<global::System.Int32> value);
        partial void OnquantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> available_Qty
        {
            get
            {
                return _available_Qty;
            }
            set
            {
                Onavailable_QtyChanging(value);
                ReportPropertyChanging("available_Qty");
                _available_Qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("available_Qty");
                Onavailable_QtyChanged();
            }
        }
        private Nullable<global::System.Int32> _available_Qty;
        partial void Onavailable_QtyChanging(Nullable<global::System.Int32> value);
        partial void Onavailable_QtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> exp_date
        {
            get
            {
                return _exp_date;
            }
            set
            {
                Onexp_dateChanging(value);
                ReportPropertyChanging("exp_date");
                _exp_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("exp_date");
                Onexp_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _exp_date;
        partial void Onexp_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onexp_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> requested_date
        {
            get
            {
                return _requested_date;
            }
            set
            {
                Onrequested_dateChanging(value);
                ReportPropertyChanging("requested_date");
                _requested_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("requested_date");
                Onrequested_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _requested_date;
        partial void Onrequested_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onrequested_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__med_id__173876EA", "check_up")]
        public EntityCollection<check_up> check_up
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<check_up>("HospitalModel1.FK__check_up__med_id__173876EA", "check_up");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<check_up>("HospitalModel1.FK__check_up__med_id__173876EA", "check_up", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new patient object.
        /// </summary>
        /// <param name="patient_id">Initial value of the patient_id property.</param>
        public static patient Createpatient(global::System.Int32 patient_id)
        {
            patient patient = new patient();
            patient.patient_id = patient_id;
            return patient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 patient_id
        {
            get
            {
                return _patient_id;
            }
            set
            {
                if (_patient_id != value)
                {
                    Onpatient_idChanging(value);
                    ReportPropertyChanging("patient_id");
                    _patient_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("patient_id");
                    Onpatient_idChanged();
                }
            }
        }
        private global::System.Int32 _patient_id;
        partial void Onpatient_idChanging(global::System.Int32 value);
        partial void Onpatient_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String patient_type
        {
            get
            {
                return _patient_type;
            }
            set
            {
                Onpatient_typeChanging(value);
                ReportPropertyChanging("patient_type");
                _patient_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("patient_type");
                Onpatient_typeChanged();
            }
        }
        private global::System.String _patient_type;
        partial void Onpatient_typeChanging(global::System.String value);
        partial void Onpatient_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String addrs
        {
            get
            {
                return _addrs;
            }
            set
            {
                OnaddrsChanging(value);
                ReportPropertyChanging("addrs");
                _addrs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("addrs");
                OnaddrsChanged();
            }
        }
        private global::System.String _addrs;
        partial void OnaddrsChanging(global::System.String value);
        partial void OnaddrsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__patien__15502E78", "check_up")]
        public EntityCollection<check_up> check_up
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<check_up>("HospitalModel1.FK__check_up__patien__15502E78", "check_up");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<check_up>("HospitalModel1.FK__check_up__patien__15502E78", "check_up", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalModel1", Name="treatment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class treatment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new treatment object.
        /// </summary>
        /// <param name="treat_id">Initial value of the treat_id property.</param>
        public static treatment Createtreatment(global::System.Int32 treat_id)
        {
            treatment treatment = new treatment();
            treatment.treat_id = treat_id;
            return treatment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 treat_id
        {
            get
            {
                return _treat_id;
            }
            set
            {
                if (_treat_id != value)
                {
                    Ontreat_idChanging(value);
                    ReportPropertyChanging("treat_id");
                    _treat_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("treat_id");
                    Ontreat_idChanged();
                }
            }
        }
        private global::System.Int32 _treat_id;
        partial void Ontreat_idChanging(global::System.Int32 value);
        partial void Ontreat_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String treat_type
        {
            get
            {
                return _treat_type;
            }
            set
            {
                Ontreat_typeChanging(value);
                ReportPropertyChanging("treat_type");
                _treat_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("treat_type");
                Ontreat_typeChanged();
            }
        }
        private global::System.String _treat_type;
        partial void Ontreat_typeChanging(global::System.String value);
        partial void Ontreat_typeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HospitalModel1", "FK__check_up__treat___164452B1", "check_up")]
        public EntityCollection<check_up> check_up
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<check_up>("HospitalModel1.FK__check_up__treat___164452B1", "check_up");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<check_up>("HospitalModel1.FK__check_up__treat___164452B1", "check_up", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
